Repository trillion-dollar-baby/autolog, pull requests merged in 2022-07, with the labels that each got.

#49 Tracking commits pushed to main into development branch as well
  autolog-api/autolog-schema.sql
  autolog-api/models/item.js
  autolog-api/routes/item.js
  autolog-ui/src/components/CreateItem/CreateItem.css
Labels: backend

#58 Settings backend: PATCH routes /auth/ and /auth/password
  autolog-api/models/user.js
  autolog-api/routes/user.js
Labels: enhancement, backend

#64 item context and create item page connected
  autolog-ui/src/components/CreateItem/CreateItem.css
  autolog-ui/src/components/CreateItem/CreateItem.jsx
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/contexts/inventory.jsx
  autolog-ui/src/contexts/item.jsx
  autolog-ui/src/contexts/items.jsx
  package-lock.json
Labels: frontend

#66 Settings, warnings, minor features
  README.md
  autolog-api/routes/inventory.js
  autolog-ui/src/components/CreateInventory/CreateInventory.jsx
  autolog-ui/src/components/Form/Form.jsx
  autolog-ui/src/components/InventoryDropdown/InventoryDropdown.jsx
  autolog-ui/src/components/Login/Login.jsx
  autolog-ui/src/components/MemberItem/MemberItem.css
  autolog-ui/src/components/MemberList/MemberList.css
  autolog-ui/src/components/MemberList/MemberList.jsx
  autolog-ui/src/components/Navbar/Navbar.jsx
  autolog-ui/src/components/Registration/Registration.jsx
  autolog-ui/src/components/RequireAuth/RequireAuth.jsx
  autolog-ui/src/components/Settings/Settings.css
  autolog-ui/src/components/Settings/Settings.jsx
  autolog-ui/src/components/SettingsMembers/SettingsMembers.css
  autolog-ui/src/components/SettingsMembers/SettingsMembers.jsx
  autolog-ui/src/components/SettingsUser/SettingsUser.jsx
  autolog-ui/src/components/Topbar/Topbar.jsx
  autolog-ui/src/contexts/auth.jsx
  autolog-ui/src/contexts/inventory.jsx
  autolog-ui/src/services/apiClient.js
Labels: enhancement, frontend, backend

#69 Inventory feature
  autolog-api/routes/item.js
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/Table/Table.jsx
  autolog-ui/src/contexts/inventory.jsx
  autolog-ui/src/contexts/items.jsx
  reflections/reflection1.md
  reflections/reflection2.md
Labels: frontend

#70 css bug updated
  autolog-ui/src/App.css
  autolog-ui/src/components/CreateItem/CreateItem.css
  autolog-ui/src/components/Dashboard/Dashboard.css
  autolog-ui/src/components/Settings/Settings.css
Labels: frontend

#71 Made loading component and added it to app. Also fixed dropdown onBlur
  autolog-ui/src/components/Dropdown/Dropdown.jsx
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/Loading/Loading.css
  autolog-ui/src/components/Loading/Loading.jsx
  autolog-ui/src/contexts/auth.jsx
  autolog-ui/src/contexts/inventory.jsx
  autolog-ui/src/contexts/items.jsx
Labels: bug

#72 Modal, dropdown onBlur different approach tested
  autolog-ui/package-lock.json
  autolog-ui/package.json
  autolog-ui/src/components/Backdrop/Backdrop.css
  autolog-ui/src/components/Backdrop/Backdrop.jsx
  autolog-ui/src/components/Dropdown/Dropdown.css
  autolog-ui/src/components/Dropdown/Dropdown.jsx
  autolog-ui/src/components/DropdownOverlay/DropdownOverlay.css
  autolog-ui/src/components/DropdownOverlay/DropdownOverlay.jsx
  autolog-ui/src/components/InventoryDropdown/InventoryDropdown.css
  autolog-ui/src/components/InventoryDropdown/InventoryDropdown.jsx
  autolog-ui/src/components/Landing/Landing.jsx
  autolog-ui/src/components/Modal/Modal.css
  autolog-ui/src/components/Modal/Modal.jsx
  autolog-ui/src/components/Modal/ModalBody.jsx
  autolog-ui/src/components/Modal/ModalFooter.jsx
  autolog-ui/src/components/Modal/ModalHeader.jsx
  autolog-ui/src/components/ModalButton/ModalButton.css
  autolog-ui/src/components/ModalButton/ModalButton.jsx
  autolog-ui/src/components/Navbar/Navbar.jsx
  autolog-ui/src/index.css
  package-lock.json
Labels: enhancement, frontend

#73 Fixed bug when creating a new inventory
  autolog-api/models/inventory.js
  autolog-ui/src/components/InventoryDropdown/InventoryDropdown.jsx
  autolog-ui/src/contexts/inventory.jsx
Labels: frontend, backend

#80 Dashboard fixes
  autolog-ui/src/App.css
  autolog-ui/src/components/Dashboard/Dashboard.css
  autolog-ui/src/components/Dashboard/Dashboard.jsx
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/Table/Table.css
  autolog-ui/src/components/Table/Table.jsx
  autolog-ui/src/contexts/items.jsx
Labels: frontend

#82 Invite button, modals, refactorizing existing modal
  autolog-ui/src/components/ButtonInvite/ButtonInvite.css
  autolog-ui/src/components/ButtonInvite/ButtonInvite.jsx
  autolog-ui/src/components/Dashboard/Dashboard.jsx
  autolog-ui/src/components/InventoryDropdown/InventoryDropdown.jsx
  autolog-ui/src/components/Modal/Modal.jsx
  autolog-ui/src/components/ModalCreateInventory/ModalCreateInventory.jsx
  autolog-ui/src/components/ModalInvite/ModalInvite.css
  autolog-ui/src/components/ModalInvite/ModalInvite.jsx
  autolog-ui/src/contexts/inventory.jsx
Labels: frontend

#84 css changes
  autolog-ui/src/assets/enzo.png
  autolog-ui/src/components/CreateInventory/CreateInventory.jsx
  autolog-ui/src/components/Landing/Landing.css
  autolog-ui/src/components/Landing/Landing.jsx
  autolog-ui/src/components/ModalCreateInventory/ModalCreateInventory.jsx
Labels: bug, frontend

#83 Table fixes
  autolog-ui/src/components/Inventory/Inventory.css
  autolog-ui/src/components/Performance/Performance.css
  autolog-ui/src/components/Performance/Performance.jsx
  autolog-ui/src/components/Table/Table.css
Labels: frontend

#85 Updated styling for settings
  autolog-ui/src/components/Settings/Settings.css
  autolog-ui/src/components/Settings/Settings.jsx
  autolog-ui/src/components/SettingsMembers/SettingsMembers.css
  autolog-ui/src/components/SettingsMembers/SettingsMembers.jsx
  autolog-ui/src/components/SettingsUser/SettingsUser.css
  autolog-ui/src/components/SettingsUser/SettingsUser.jsx
Labels: frontend

#86 inventory Lookup date formatting changes
  autolog-api/autolog-schema.sql
  autolog-api/models/item.js
Labels: backend

#87 Performance backend
  autolog-api/app.js
  autolog-api/autolog-schema.sql
  autolog-api/models/item.js
  autolog-api/models/performance.js
  autolog-api/routes/inventory.js
  autolog-api/routes/item.js
  autolog-api/routes/performance.js
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/Performance/Performance.css
  autolog-ui/src/components/Performance/Performance.jsx
  autolog-ui/src/components/SettingsMembers/SettingsMembers.css
  autolog-ui/src/contexts/items.jsx
  autolog-ui/src/contexts/performance.jsx
  autolog-ui/src/index.css
  autolog-ui/src/main.jsx
  autolog-ui/src/services/apiClient.js
Labels: frontend, backend

#88 Item create detail: Categories backend
  autolog-api/.editorconfig
  autolog-api/app.js
  autolog-api/models/category.js
  autolog-api/routes/category.js
  autolog-ui/src/components/Dropdown/Dropdown.jsx
Labels: enhancement, backend

#90 Item create, styling updates, settings page, animations
  autolog-api/models/category.js
  autolog-api/models/user.js
  autolog-ui/src/App.jsx
  autolog-ui/src/components/Backdrop/Backdrop.css
  autolog-ui/src/components/Button/ButtonAction.css
  autolog-ui/src/components/Button/ButtonAction.jsx
  autolog-ui/src/components/CreateItem/CreateItem.css
  autolog-ui/src/components/CreateItem/CreateItem.jsx
  autolog-ui/src/components/Dropdown/Dropdown.css
  autolog-ui/src/components/DropdownCategory/DropdownCategory.css
  autolog-ui/src/components/DropdownCategory/DropdownCategory.jsx
  autolog-ui/src/components/DropdownCategory/DropdownCategoryItem.jsx
  autolog-ui/src/components/Form/Form.css
  autolog-ui/src/components/FormInput/FormInput.css
  autolog-ui/src/components/ItemDetail/ItemDetail.css
  autolog-ui/src/components/ItemDetail/ItemDetail.jsx
  autolog-ui/src/components/MemberList/MemberList.css
  autolog-ui/src/components/Modal/Modal.css
  autolog-ui/src/components/ModalButton/ModalButton.css
  autolog-ui/src/components/ModalButton/ModalButton.jsx
  autolog-ui/src/components/ModalCreateCategory/ModalCreateCategory.jsx
  autolog-ui/src/components/Settings/Settings.jsx
  autolog-ui/src/components/SettingsUser/SettingsUser.css
  autolog-ui/src/components/SettingsUser/SettingsUser.jsx
  autolog-ui/src/components/TextArea/TextArea.css
  autolog-ui/src/components/TextArea/TextArea.jsx
  autolog-ui/src/contexts/items.jsx
  autolog-ui/src/index.css
  autolog-ui/src/services/apiClient.js
Labels: enhancement, frontend

#91 Search function for inventory lookup page
  autolog-ui/src/assets/delandwithcat.jpg
  autolog-ui/src/assets/wynee.jpg
  autolog-ui/src/components/Dashboard/Dashboard.css
  autolog-ui/src/components/FormInput/FormInput.jsx
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/Landing/Landing.css
  autolog-ui/src/components/Landing/Landing.jsx
  autolog-ui/src/contexts/items.jsx
Labels: frontend

#92 css hotfix for createItem
  autolog-ui/src/components/CreateItem/CreateItem.css
  autolog-ui/src/components/CreateItem/CreateItem.jsx
Labels: bug, frontend

#93 Performance backend
  autolog-api/models/item.js
  autolog-api/models/performance.js
  autolog-api/routes/performance.js
  autolog-ui/src/components/Dropdown/Dropdown.css
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/Performance/Performance.css
  autolog-ui/src/components/Performance/Performance.jsx
  autolog-ui/src/contexts/performance.jsx
  autolog-ui/src/services/apiClient.js
Labels: frontend, backend

#94 Bugfixes, transitions added
  autolog-api/autolog-schema.sql
  autolog-api/models/inventory.js
  autolog-api/models/item.js
  autolog-api/models/user.js
  autolog-api/package-lock.json
  autolog-api/package.json
  autolog-api/routes/item.js
  autolog-api/routes/user.js
  autolog-ui/src/components/CreateItem/CreateItem.jsx
  autolog-ui/src/components/Dashboard/Dashboard.jsx
  autolog-ui/src/components/DropdownCategory/DropdownCategory.css
  autolog-ui/src/components/DropdownCategory/DropdownCategory.jsx
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/InventoryDropdown/InventoryDropdown.jsx
  autolog-ui/src/components/ItemDetail/ItemDetail.css
  autolog-ui/src/components/ItemDetail/ItemDetail.jsx
  autolog-ui/src/components/Performance/Performance.jsx
  autolog-ui/src/components/SettingsUser/SettingsUser.jsx
  autolog-ui/src/components/Sidebar/Sidebar.css
  autolog-ui/src/contexts/auth.jsx
  autolog-ui/src/contexts/items.jsx
  autolog-ui/src/services/apiClient.js
Labels: bug, frontend, backend

#97 Inventory filter
  autolog-ui/src/components/Dashboard/Dashboard.css
  autolog-ui/src/components/FormInput/FormInput.css
  autolog-ui/src/components/Inventory/Inventory.css
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/Landing/Landing.css
  autolog-ui/src/components/Login/Login.css
  autolog-ui/src/components/Performance/Performance.jsx
  autolog-ui/src/contexts/items.jsx
Labels: frontend

#98 Toast feature
  autolog-ui/.editorconfig
  autolog-ui/package-lock.json
  autolog-ui/package.json
  autolog-ui/src/App.jsx
  autolog-ui/src/components/SettingsUser/SettingsUser.jsx
  autolog-ui/src/contexts/toast.jsx
  autolog-ui/src/main.jsx
Labels: frontend, stretch feature

#100 Fixed page
  autolog-ui/src/components/Inventory/Inventory.css
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/contexts/items.jsx
Labels: bug

#103 Added toasts to successful/failed requests
  autolog-ui/src/components/CreateItem/CreateItem.jsx
  autolog-ui/src/components/ItemDetail/ItemDetail.jsx
  autolog-ui/src/components/ModalCreateCategory/ModalCreateCategory.jsx
  autolog-ui/src/components/ModalCreateInventory/ModalCreateInventory.jsx
  autolog-ui/src/contexts/toast.jsx
Labels: enhancement, frontend

#104 Random bug fixes
  autolog-api/models/item.js
  autolog-ui/src/components/MemberItem/MemberItem.css
  autolog-ui/src/components/MemberItem/MemberItem.jsx
  autolog-ui/src/components/SettingsUser/SettingsUser.css
  autolog-ui/src/contexts/items.jsx
  autolog-ui/src/contexts/performance.jsx
Labels: bug

#106 CSS tweaks
  autolog-ui/src/components/ButtonInvite/ButtonInvite.jsx
  autolog-ui/src/components/Dashboard/Dashboard.css
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/Modal/Modal.css
  autolog-ui/src/components/ModalButton/ModalButton.jsx
  autolog-ui/src/components/ModalInvite/ModalInvite.jsx
  autolog-ui/src/components/Table/Table.css
Labels: enhancement
