Repository trillion-dollar-baby/autolog, pull requests merged in 2022-08, with the labels that each got.

#113 Logs backend
  autolog-api/app.js
  autolog-api/autolog-schema.sql
  autolog-api/models/category.js
  autolog-api/models/inventory.js
  autolog-api/models/item.js
  autolog-api/models/log.js
  autolog-api/models/performance.js
  autolog-api/models/user.js
  autolog-api/routes/item.js
  autolog-api/routes/log.js
  autolog-ui/src/components/CreateItem/CreateItem.jsx
  autolog-ui/src/components/Dashboard/Dashboard.css
  autolog-ui/src/components/Dashboard/Dashboard.jsx
  autolog-ui/src/components/Inventory/Inventory.css
  autolog-ui/src/components/ModalInvite/ModalInvite.jsx
  autolog-ui/src/components/Performance/Performance.css
  autolog-ui/src/components/Table/Table.css
  autolog-ui/src/components/Table/Table.jsx
  autolog-ui/src/contexts/dashboard.jsx
  autolog-ui/src/main.jsx
  autolog-ui/src/services/apiClient.js
Labels: frontend, backend, stretch feature

#114 Dashboard backend
  autolog-api/app.js
  autolog-api/models/dashboard.js
  autolog-api/routes/dashboard.js
Labels: backend

#116 Dashboard backend
  autolog-api/autolog-schema.sql
  autolog-api/models/dashboard.js
  autolog-api/routes/dashboard.js
Labels: backend

#115 User Roles implementation and integration with frontend
  README.md
  autolog-api/autolog-schema.sql
  autolog-api/middleware/permissions.js
  autolog-api/models/inventory.js
  autolog-api/models/role.js
  autolog-api/routes/inventory.js
  autolog-api/routes/item.js
  autolog-ui/src/components/Dropdown/Dropdown.jsx
  autolog-ui/src/components/MemberItem/MemberItem.jsx
  autolog-ui/src/components/MemberList/MemberList.jsx
  autolog-ui/src/components/ModalInvite/ModalInvite.jsx
  autolog-ui/src/components/RequireAuth/RequireAuth.jsx
  autolog-ui/src/components/SettingsMembers/SettingsMembers.jsx
  autolog-ui/src/contexts/inventory.jsx
  autolog-ui/src/services/apiClient.js
  reflections/reflection2.md
Labels: enhancement, frontend, backend, stretch feature

#117 UI for role settings, Backend for roles created, Backend changes for better organization
  autolog-api/app.js
  autolog-api/models/inventory.js
  autolog-api/models/role.js
  autolog-api/routes/inventory.js
  autolog-api/routes/member.js
  autolog-api/routes/role.js
  autolog-ui/src/components/Button/ButtonAction.jsx
  autolog-ui/src/components/MemberItem/MemberItem.css
  autolog-ui/src/components/RoleAbility/RoleAbility.css
  autolog-ui/src/components/RoleAbility/RoleAbility.jsx
  autolog-ui/src/components/RoleItem/RoleItem.css
  autolog-ui/src/components/RoleItem/RoleItem.jsx
  autolog-ui/src/components/RoleList/RoleList.css
  autolog-ui/src/components/RoleList/RoleList.jsx
  autolog-ui/src/components/Settings/Settings.jsx
  autolog-ui/src/components/SettingsMembers/SettingsMembers.css
  autolog-ui/src/components/SettingsMembers/SettingsMembers.jsx
  autolog-ui/src/components/SettingsRoles/SettingsRoles.css
  autolog-ui/src/components/SettingsRoles/SettingsRoles.jsx
  autolog-ui/src/contexts/role.jsx
  autolog-ui/src/main.jsx
  autolog-ui/src/services/apiClient.js
Labels: enhancement, frontend, backend, stretch feature

#118 Email confirmation feature
  autolog-api/.env.template
  autolog-api/app.js
  autolog-api/autolog-schema.sql
  autolog-api/models/confirmation.js
  autolog-api/models/user.js
  autolog-api/routes/confirmation.js
  autolog-api/routes/user.js
  autolog-api/utils/tokens.js
  autolog-ui/src/App.jsx
  autolog-ui/src/components/EmailConfirmation/EmailConfirmation.css
  autolog-ui/src/components/EmailConfirmation/EmailConfirmation.jsx
  autolog-ui/src/components/Landing/Landing.jsx
  autolog-ui/src/components/Login/Login.jsx
  autolog-ui/src/components/Registration/Registration.jsx
  autolog-ui/src/components/RequireAuth/RequireAuth.jsx
  autolog-ui/src/components/Sidebar/Sidebar.jsx
  autolog-ui/src/contexts/auth.jsx
  autolog-ui/src/contexts/inventory.jsx
  package-lock.json
  package.json
Labels: frontend, backend, stretch feature

#121 Basic role check for Frontend and Backend
  autolog-api/middleware/permissions.js
  autolog-api/models/inventory.js
  autolog-api/models/member.js
  autolog-api/models/role.js
  autolog-api/routes/member.js
  autolog-api/routes/role.js
  autolog-ui/src/components/Dropdown/Dropdown.jsx
  autolog-ui/src/components/MemberItem/MemberItem.jsx
  autolog-ui/src/components/MemberList/MemberList.jsx
  autolog-ui/src/components/ModalCreateRole/ModalCreateRole.jsx
  autolog-ui/src/components/ModalModifyRole/ModalModifyRole.jsx
  autolog-ui/src/components/PermissionCheckbox/PermissionCheckbox.jsx
  autolog-ui/src/components/RoleItem/RoleItem.jsx
  autolog-ui/src/components/RoleList/RoleList.jsx
  autolog-ui/src/components/SettingsRoles/SettingsRoles.jsx
  autolog-ui/src/components/UnauthorizedPage/UnauthorizedPage.jsx
  autolog-ui/src/contexts/inventory.jsx
  autolog-ui/src/contexts/role.jsx
  autolog-ui/src/services/apiClient.js
Labels: enhancement, frontend, backend

#120 Modify role finished
  autolog-api/models/role.js
  autolog-api/routes/role.js
  autolog-ui/src/components/ModalCreateRole/ModalCreateRole.jsx
  autolog-ui/src/components/ModalModifyRole/ModalModifyRole.jsx
  autolog-ui/src/components/PermissionCheckbox/PermissionCheckbox.jsx
  autolog-ui/src/components/RoleItem/RoleItem.jsx
  autolog-ui/src/components/RoleList/RoleList.jsx
  autolog-ui/src/components/SettingsRoles/SettingsRoles.jsx
  autolog-ui/src/contexts/role.jsx
  autolog-ui/src/services/apiClient.js
Labels: enhancement, frontend, backend

#122 Dashboardconnectto frontend
  autolog-api/.env.template
  autolog-api/models/dashboard.js
  autolog-api/routes/dashboard.js
  autolog-ui/src/components/Dashboard/Checklist.jsx
  autolog-ui/src/components/Dashboard/Dashboard.css
  autolog-ui/src/components/Dashboard/Dashboard.jsx
  autolog-ui/src/components/ModalCreateCategory/ModalCreateCategory.jsx
  autolog-ui/src/contexts/dashboard.jsx
  autolog-ui/src/services/apiClient.js
Labels: frontend

#125 created constants.js to get api base url based on what mode is the ap…
  autolog-api/constants.js
  autolog-api/models/confirmation.js
  autolog-api/routes/confirmation.js
  autolog-ui/src/constants.js
  autolog-ui/src/services/apiClient.js
Labels: enhancement, frontend

#129 Infinite scrolling feature
  autolog-api/constants.js
  autolog-api/models/item.js
  autolog-ui/src/components/Inventory/Inventory.css
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/Table/Table.css
  autolog-ui/src/components/Table/Table.jsx
  autolog-ui/src/services/apiClient.js
Labels: frontend

#131 Dashboardconnectto frontend
  autolog-api/models/dashboard.js
  autolog-api/routes/dashboard.js
  autolog-ui/src/components/Dashboard/Checklist.jsx
  autolog-ui/src/contexts/dashboard.jsx
  autolog-ui/src/services/apiClient.js
Labels: frontend, backend

#150 Accessibilityhints
  autolog-api/constants.js
  autolog-ui/src/assets/question-mark-icon.png
  autolog-ui/src/components/Dashboard/Checklist.jsx
  autolog-ui/src/components/Dashboard/Dashboard.css
  autolog-ui/src/components/Dashboard/Dashboard.jsx
  autolog-ui/src/components/Dropdown/Dropdown.css
  autolog-ui/src/components/Form/Form.css
  autolog-ui/src/components/Inventory/Inventory.css
  autolog-ui/src/components/Inventory/Inventory.jsx
  autolog-ui/src/components/InventoryDropdown/InventoryDropdown.jsx
  autolog-ui/src/components/Modal/Modal.css
  autolog-ui/src/components/ModalModifyRole/ModalModifyRole.jsx
  autolog-ui/src/components/Performance/Performance.css
  autolog-ui/src/components/Performance/Performance.jsx
  autolog-ui/src/components/PermissionCheckbox/PermissionCheckbox.css
  autolog-ui/src/components/PermissionCheckbox/PermissionCheckbox.jsx
  autolog-ui/src/components/RoleList/RoleList.css
  autolog-ui/src/components/RoleList/RoleList.jsx
  autolog-ui/src/components/SettingsUser/SettingsUser.css
  autolog-ui/src/components/SettingsUser/SettingsUser.jsx
  autolog-ui/src/components/Table/Table.css
  autolog-ui/src/components/Table/Table.jsx
  autolog-ui/src/contexts/dashboard.jsx
Labels: enhancement, frontend

#155 Css fixes
  autolog-ui/src/components/Dashboard/Dashboard.css
  autolog-ui/src/components/Inventory/Inventory.jsx
Labels: frontend
